// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoRequest(arg1) {
  return window['go']['main']['App']['DoRequest'](arg1);
}

export function GetSavedRequestsInWorkspace() {
  return window['go']['main']['App']['GetSavedRequestsInWorkspace']();
}

export function SaveRequest(arg1) {
  return window['go']['main']['App']['SaveRequest'](arg1);
}
