// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http_types} from '../models';

export function DoRequest(arg1:string,arg2:string):Promise<http_types.Response>;
