// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http_types} from '../models';

export function DoRequest(arg1:http_types.Request):Promise<http_types.Response>;

export function GetSavedRequestsInWorkspace():Promise<{[key: string]: any}>;

export function SaveRequest(arg1:string):Promise<boolean>;
